[package]
name = "unlambda"
version = "0.1.0"
authors = ["Vlad Shcherbina <vlad.shcherbina@gmail.com>"]
edition = "2018"

[dependencies]
rc_stack = { path = "rc_stack" }
clap = "*"
structopt = "*"
time = "*"

[workspace]
