name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: [cron: "35 23 * * *"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            components: clippy
            override: true
      - uses: Swatinem/rust-cache@v1
      - name: cargo fetch
        uses: actions-rs/cargo@v1
        with:
          command: fetch
          args: --locked
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=mimalloc --all
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=mimalloc --all
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
